In [ ]:
import sys
from pathlib import Path
import logging

project_root = Path.cwd().parent
sys.path.append(str(project_root))

logging.getLogger().setLevel(logging.WARNING)

In [ ]:
#PAYROLL
from config import CONFIG
from src.ingestion import ingest_all_sources
ingest= ingest_all_sources(CONFIG["input_dir"])
df=ingest["globaltech_hris"]

#df["source"].unique()
df.head(5)

In [20]:
#AquiredCo
ingest= ingest_all_sources(CONFIG["input_dir"])
df=ingest["acquiredco_hris"]
df.head(5)

,employee_id,first_name,last_name,email,department,job_title,hire_date,country,employment_type,manager_id,source
0,ACQ_00001,Larry,Smith,larry.smith@acquiredco.com,Product,Controller,2024-06-27 00:00:00,Mexico,PT,ACQ_02436,acquiredco
1,ACQ_00002,Michael,Crawford,michael.crawford@acquiredco.com,Legal,Controller,2021-06-09 00:00:00,Japan,PT,ACQ_02546,acquiredco
2,ACQ_00003,Brandon,Moore,brandon.moore@acquiredco.com,Marketing,Solutions Architect,2022-06-20 00:00:00,United States,CONTRACTOR,ACQ_01415,acquiredco
3,ACQ_00004,Ashley,Moore,ashley.moore@acquiredco.com,Marketing,Product Manager,2022-04-27 00:00:00,Netherlands,CONTRACTOR,ACQ_01247,acquiredco
4,ACQ_00005,Rachel,Clark,rachel.clark@acquiredco.com,Sales,Solutions Architect,2017-05-01 00:00:00,France,PT,ACQ_02354,acquiredco
...,...,...,...,...,...,...,...,...,...,...,...
3195,ACQ_DUP_00195,Patric,Parker,patrick.parker@acquiredco.com,Product,Systems Administrator,2015-07-20 00:00:00+00:00,Ireland,PT,None,acquiredco
3196,ACQ_DUP_00196,Maggie,Martinez,margaret.martinez@acquiredco.com,Manufacturing,Data Scientist,2016-11-09 00:00:00+00:00,United Kingdom,CONTRACTOR,None,acquiredco
3197,ACQ_DUP_00197,Joe,Lopez,joseph.lopez@acquiredco.com,Product,Data Analyst,2020-04-09 00:00:00+00:00,Japan,CONTRACTOR,None,acquiredco
3198,ACQ_DUP_00198,Sus,Collins,susan.collins@acquiredco.com,Supply Chain,Senior Product Manager,2021-03-24 00:00:00+00:00,Sweden,FT,None,acquiredco
3199,ACQ_DUP_00199,Rac,White,rachel.white@acquiredco.com,DevOps,Solutions Architect,2022-09-24 00:00:00+00:00,Germany,PT,None,acquiredco

In [ ]:
#PAYROLL
ingest= ingest_all_sources(CONFIG["input_dir"])
df=ingest["payroll"]

#df["source"].unique()
df.head(5)

In [21]:
#PAYROLL
ingest= ingest_all_sources(CONFIG["input_dir"])
df=ingest["benefits"]

#df["source"].unique()
df.head(5)

,employee_id,plan_type,coverage_level,enrollment_date,premium_employee,premium_employer,source
0,2239,Vision,Family,2024-03-23,54.50,469.17,benefits
1,7612,401(k),Employee+Spouse,2021-06-14,188.19,705.57,benefits
2,12967,Life Insurance,Employee+Child,2020-07-26,63.50,261.07,benefits
3,12133,Health Insurance,Employee+Child,2024-05-25,213.74,875.07,benefits
4,14962,Life Insurance,Individual,2024-08-04,272.75,911.80,benefits